### PR TITLE
bug: fix querier return empty array

### LINKED ISSUE #100: [Bug] Nil pointer on querier
nil pointer when argument doesn't exist

```
go run . get vdc --name toto
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/orange-cloudavenue/cloudavenue-sdk-go/v1.(*Get).VDC(...)
        /Users/micheneaudavid/go/pkg/mod/github.com/orange-cloudavenue/cloudavenue-sdk-go@v0.10.0/v1/querier.go:115
github.com/orange-cloudavenue/cloudavenue-cli/cmd.init.func13(0x102463e00, {0x10141dd60?, 0x4?, 0x10141dc7c?})
        /Users/micheneaudavid/go/src/github.com/orange-cloudavenue/cloudavenue-cli/cmd/get_vdc.go:40 +0x880
github.com/spf13/cobra.(*Command).execute(0x102463e00, {0x140005ae3c0, 0x2, 0x2})
        /Users/micheneaudavid/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x1024640e0)
        /Users/micheneaudavid/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/micheneaudavid/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/orange-cloudavenue/cloudavenue-cli/cmd.Execute()
        /Users/micheneaudavid/go/src/github.com/orange-cloudavenue/cloudavenue-cli/cmd/root.go:26 +0x68
main.main()
        /Users/micheneaudavid/go/src/github.com/orange-cloudavenue/cloudavenue-cli/main.go:18 +0x20
exit status 2
```

### PR DESCRIPTION
**Pull request by dmicheneau**
```
go run . get vdc --name toto
[]      >>>>  []vdc: (*types.QueryResultOrgVdcRecordType)(nil)Usage:
  cav get vdc [flags]
...

** Error **: Command return an Error: CloudAvenue Error from VDC Get (VDC exist ?): %!w(<nil>)
exit status 1

```

The code was tested from cav binary successfully.

### CODE REVIEW

**Comment by dmicheneau** [comment]
The querier do not return an error, so now the sdk return a nil object if doesn't exist.

File: v1/querier.go [hunk 1]
```diff
@@ -124,6 +127,9 @@ func (q *List) VAPP() ([]*types.QueryResultVAppRecordType, error) {
 // VAPP get a vapp informations by name
 func (q *Get) VAPP(vappName string) (*types.QueryResultVAppRecordType, error) {
 	r, err := queryGet(typeVAPP, vappName)
+	if r.Results.OrgVdcRecord == nil {
```
Comment (azrod) [inline v1/querier.go]: VappRecord

**Review by azrod — CHANGES_REQUESTED** [review]

**Review by azrod — APPROVED** [review]
